server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/registration
    username: postrges
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgresSQLDialect




